module.exports = {
  english: { // General
    mainTitle: 'easy Naz',
    help: 'Help',
    filtersChosen: 'Filter Chosen',
    submit: 'Get Results',
    nextAria: 'go to the next page',
    next: 'Next',
    back: 'go back to the previous page',
    homePage: 'Go-back-to-the-Start',
    serviceTitle: 'Services Page',
    homeIcon: 'Icon for the home page',
    helpIcon: 'Icon for the help button',
    helpInfo: 'easyNaz is made in aim to let people know of the few accissible places in Nazareth and encourage more businesses to become accessible! In our app you can find all the accessible places and businesses in Nazrareth anytime and just a few clicks depends on what you need or looking for.',
    notFound: 'Sorry we have no services in our database that match your selections',
    // Disabilities page
    disabilitiesPrompt: 'Select the Disability or Disabilities you want to be catered for',
    visual: 'Visual',
    physical: 'Physical',
    aural: 'Aural',
    mental: 'Mental',
    // Services page
    serviceQuesion: 'What kind of service are you looking for',
    food: 'Food',
    shopping: 'Shopping',
    religion: 'Religion',
    health: 'Health',
    viewPoints: 'View Points',
    nature: 'Nature',
    museums: 'Museums',
    // Service Info Page
    accessTitle: 'Accessibility options',
    address: 'Address',
    desc: 'Description ',
    opens: 'Opening Hours ',
    contact: 'Contact details',
    phone: 'Phone Number ',
    email: 'Email '
  },
  arabic: { // General
    mainTitle: 'easy Naz',
    help: ' مساعده',
    filtersChosen: 'الامكانيات المختارة ',
    submit: 'اعرض النتائج ',
    nextAria: ' اذهب الى الصفحه التالية',
    next: 'التالي ',
    back: 'العوده صفحه الى الوراء ',
    homePage: 'العوده الى الصفحه الرئيسيه ',
    serviceTitle: 'صفحة الخدمات ',
    homeIcon: ' ايقونه الصفحه الرئيسيه ',
    helpIcon: ' ايقونه للمساعده',
    helpInfo: ' هذا التطبيق بني بهدف مساعدة الناس على التعرف على بعض الاماكن في الناصرة التي توفر خدمات لذوي الاحتياجات الخاصة ولتشجيع اصحاب المصالح التجارية لادخال هذة الخدمات ضمن عملهم ومن خلال تطبيقنا تستطيع ان تجد اي خدمة تبحث عنها في اي وقت هي مجرد كبسة زر حتى تجد ما تبحث عنه',
    notFound: ' نعتذر لا يوجد لدينا في قاعده البيانات معلومات متطابقه لاختياراتك ',

    // Disabilities page
    disabilitiesPrompt: 'حدد نوع الاعاقة او الاعاقات التي تهمك ',
    visual: 'بصري',
    physical: 'جسدي',
    aural: 'سمعي',
    mental: 'عقلي',
    // Services page
    serviceQuesion: 'ما نوع الخدمة او الخدمات التي تبحث عنها ',
    food: 'طعام',
    shopping: 'مشتريات',
    religion: 'ديانات',
    health: 'صحة',
    viewPoints: 'مناظر',
    nature: 'طبيعة',
    museums: 'متاحف',
    // Service Info Page
    accessTitle: 'الخدمات المتاحة ',
    address: 'العنوان',
    desc: 'تفاصيل ',
    opens: ' ساعات العمل ',
    contact: 'للتواصل ',
    phone: 'رقم الهاتف ',
    email: ' الايميل '
  }
}
